{
 "title": "goMysqlSr dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "jobName", "label": "jobName", "query": { "query": "label_values(job)" } },
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(go_mysql_sr_start_time{job=\"$jobName\"},instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "运行时间",
   "type": "stat",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - go_mysql_sr_start_time{job=\"$jobName\", instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "运行状态",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "go_info{job=\"$jobName\", instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "读取消息数QPS",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "rate(go_mysql_sr_read_processed_ops_total{job=\"$jobName\", instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "写入消息数QPS",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 6 },
   "targets": [
    {
     "expr": "rate(go_mysql_sr_write_processed_ops_total{job=\"$jobName\", instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "读取延迟",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "go_mysql_sr_read_delay_time_seconds{job=\"$jobName\", instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "写入延迟",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "go_mysql_sr_write_delay_time_seconds{job=\"$jobName\", instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "总延迟（读取延迟+写入延迟）",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "go_mysql_sr_read_delay_time_seconds{job=\"$jobName\", instance=~\"$instance\"} + go_mysql_sr_write_delay_time_seconds{job=\"$jobName\", instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "延迟消息数（读取消息数-写入消息数）",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "go_mysql_sr_read_processed_ops_total{job=\"$jobName\", instance=~\"$instance\"} - go_mysql_sr_write_processed_ops_total{job=\"$jobName\", instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}